apiVersion: v1
kind: Service
metadata:
  name: fe-web-svc
  namespace: fe-web
spec:
  selector:
    app: fe-webapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  # no to random ips!!!
  clusterIP: 10.107.154.20
  # Cluster ip for now
  type: ClusterIP